do some retries inside the migrate job while awaiting startup

diff --git a/templates/migrate-postgres-job.yaml b/templates/migrate-postgres-job.yaml
--- a/templates/migrate-postgres-job.yaml
+++ b/templates/migrate-postgres-job.yaml
@@ -16,10 +16,22 @@ data:
     # OLDHOST and PGDATABASE need to have been set as environment variables
     export PGPASSWORD=$POSTGRESQL_PASSWORD
     export PGUSER=${PGUSER:=postgres}
+    export MAX_RETRIES=${MAX_RETIRES:=10}
     
-    # copy "globals" (users/roles)
-    # exclude the 'postgres' user since that one was defined with initdb
-    pg_dumpall -h $OLDHOST -U postgres -g | grep -v 'ROLE postgres' | psql -d postgres
+    # may have to try a few times while server pod is being brought up
+    i=1
+    while true; do
+      # copy "globals" (users/roles)
+      # exclude the 'postgres' user since that one was defined with initdb
+      pg_dumpall -h $OLDHOST -U postgres -g | grep -v 'ROLE postgres' | psql -d postgres && break || echo "failed, try $i"
+      if [ $i -ge $MAX_RETRIES ]; then
+        echo "Maximum retries, exiting"
+        exit -1
+      fi
+      sleep 20
+      ((i++))
+    done
+    echo "hey, it worked this time!"
     
     # increase max_wal_size (temporarily) since we're about to do a lot of inserts
     psql -d postgres <<EOSQL
